### ISSUE TITLE
'module.export' should be 'module.exports'

### ISSUE THREAD

**Issue by yhirose** [andyrj/hyperapp-redux-devtools#2]
Thanks for the very useful module.
I just discovered a problem with the module export code in the recent change.
I guess it should be 'module.exports' instead of 'module.export'.

https://github.com/andyrj/hyperapp-redux-devtools/commit/d92fefb61dc25d2b73fcd88e075726911457ddc9#diff-168726dbe96b3ce427e7fedce31bb0bcR15

**Comment by andyrj** [comment]
Thank you for spotting the error and for the PR!
