### ISSUE TITLE
state not updated with async action when using devtools

### ISSUE THREAD

**Issue by adekbadek** [andyrj/hyperapp-redux-devtools#6]
When using devtools HOA, an async action does not update state
Here is a demo - https://codesandbox.io/s/5938y1onl

**Comment by yhirose** [comment]
@adekbadek, before the version 1.1.3 arrives, you can fix it with making the following change by hand at line no. 26 in node_modules/hyperapp-redux-devtools/index.js. (`actions` to `appActions`)

```js:node_modules/hyperapp-redux-devtools/index.js
26 -        var result = act.apply(this, arguments)(appActions.getState(), actions);
26 +        var result = act.apply(this, arguments)(appActions.getState(), appActions);
```

Hope it helps.

**Comment by andyrj** [comment]
I will publish correction for this to npm this morning.  Sorry for delayed response.

**Comment by andyrj** [comment]
version 1.1.3 is on npm now with fix for async actions
