### ISSUE TITLE
Recommended boilerplate to only import redux during dev?

### ISSUE THREAD

**Issue by selfup** [andyrj/hyperapp-redux-devtools#8]
Should the end user do something like:

```js
let main;

if (process.env.NODE_ENV !== 'production') {
  import('hyperapp-redux-devtools')
    .then((devtools) => {
      main = devtools(app)(...);
    });
} else {
  main = app(...);
}
```

Just wondering how we can avoid pushing up code in prod that is only needed in dev! 🚀

**Comment by andyrj** [comment]
Ya that totally works, you can also just use require conditionally inline, if your using a bundler.

**Comment by selfup** [comment]
Ok awesome 🎉

**Comment by tkivela** [comment]
works here too, except I think @selfup had a typo in the code, should be 
process.env.NODE_ENV

**Comment by selfup** [comment]
@tkivela good catch 👍

**Comment by andyrj** [comment]
Should we add this to the readme?

**Comment by selfup** [comment]
Not a bad idea!

We would need to provide conditional require as well as the webpack import syntax. But other than that I see nothing but benefits putting this in the README

**Comment by andyrj** [comment]
examples have been added to README
